# Generated by Django 6.0 on 2026-01-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="notesuser",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
