# Generated by Django 6.0 on 2026-02-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_alter_notes_created_at_alter_notesuser_created_at"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notes",
            new_name="Note",
        ),
    ]
