name: Pipeline Workflow

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]


jobs:
    code_quality_checks:
        uses: ./.github/workflows/checks.yaml
    build_container_image:
        uses: ./.github/workflows/build.yaml
    security_analysis:
        uses: ./.github/workflows/security.yaml